import 'dart:convert';
import '../../core/constants/app_strings.dart';

/// Status of expense detection performed by Gemma model.
enum ExpenseDetectionStatus {
  complete,
  incomplete,
  notAnExpense,
}

/// Holds the analysis result from Gemma model expense detection.
class ExpenseDetectionResult {
  final ExpenseDetectionStatus status;
  final ExpenseDetails? expense;
  final String? failureReason;
  final String rawOutput;

  const ExpenseDetectionResult({
    required this.status,
    this.expense,
    this.failureReason,
    required this.rawOutput,
  });

  bool get isComplete => status == ExpenseDetectionStatus.complete;

  /// Returns a standardized formatted response for the user, printing raw model output first.
  String toFormattedResponse() {
    final buffer = StringBuffer();

    final cleanRaw = rawOutput.trim();
    buffer.writeln('🤖 Model Output:');
    buffer.writeln(cleanRaw.isEmpty ? '(No output generated by model)' : cleanRaw);
    buffer.writeln('----------------------------------------');

    switch (status) {
      case ExpenseDetectionStatus.complete:
        if (expense != null) {
          buffer.writeln('✅ Expense Detected Successfully');
          buffer.writeln('💵 Amount: ${expense!.currency} ${expense!.amount}');
          buffer.writeln('🏷️ Category: ${expense!.category}');
          if (expense!.merchant != null) buffer.writeln('🏪 Merchant: ${expense!.merchant}');
          if (expense!.date != null) buffer.writeln('📅 Date: ${expense!.date}');
          if (expense!.description != null) buffer.writeln('📝 Description: ${expense!.description}');
          buffer.writeln('----------------------------------------');
          buffer.write('Status: Complete');
        } else {
          buffer.write('⚠️ Expense detection incomplete.');
        }
        break;

      case ExpenseDetectionStatus.incomplete:
        buffer.writeln('⚠️ Incomplete Expense Details');
        if (failureReason != null) buffer.writeln('Reason: $failureReason');
        buffer.writeln('----------------------------------------');
        buffer.write('Status: Incomplete');
        break;

      case ExpenseDetectionStatus.notAnExpense:
        buffer.writeln('ℹ️ No Expense Detected');
        buffer.writeln('----------------------------------------');
        buffer.write('Status: Not an Expense');
        break;
    }

    return buffer.toString();
  }
}

/// A model-detected expense.
class ExpenseDetails {
  final num amount;
  final String currency;
  final String category;
  final String? merchant;
  final String? date;
  final String? description;

  const ExpenseDetails({
    required this.amount,
    required this.currency,
    required this.category,
    this.merchant,
    this.date,
    this.description,
  });

  /// Evaluates Gemma model response to check if expense detection is complete or not,
  /// returning an [ExpenseDetectionResult].
  static ExpenseDetectionResult parseResponse(String rawResponse) {
    final trimmed = rawResponse.trim();
    if (trimmed.isEmpty) {
      return ExpenseDetectionResult(
        status: ExpenseDetectionStatus.notAnExpense,
        failureReason: 'Model response was empty.',
        rawOutput: rawResponse,
      );
    }

    String jsonCandidate = trimmed;
    if (!jsonCandidate.startsWith('{')) {
      final firstBrace = jsonCandidate.indexOf('{');
      if (firstBrace >= 0) {
        jsonCandidate = jsonCandidate.substring(firstBrace);
      } else {
        jsonCandidate = '{$jsonCandidate';
      }
    }

    final jsonStart = jsonCandidate.indexOf('{');
    final jsonEnd = jsonCandidate.lastIndexOf('}');

    if (jsonStart < 0 || jsonEnd < jsonStart) {
      return ExpenseDetectionResult(
        status: ExpenseDetectionStatus.incomplete,
        failureReason: 'Malformed model output (no JSON structure found).',
        rawOutput: rawResponse,
      );
    }

    try {
      final jsonString = jsonCandidate.substring(jsonStart, jsonEnd + 1);
      final decoded = jsonDecode(jsonString);

      if (decoded is! Map<String, dynamic>) {
        return ExpenseDetectionResult(
          status: ExpenseDetectionStatus.incomplete,
          failureReason: 'JSON response is invalid object.',
          rawOutput: rawResponse,
        );
      }

      if (decoded['is_expense'] == false) {
        return ExpenseDetectionResult(
          status: ExpenseDetectionStatus.notAnExpense,
          failureReason: 'Text does not describe an expense.',
          rawOutput: rawResponse,
        );
      }

      num? parsedAmount;
      if (decoded['amount'] is num) {
        parsedAmount = decoded['amount'];
      } else if (decoded['amount'] is String) {
        parsedAmount = num.tryParse(
          decoded['amount'].replaceAll(RegExp(r'[^0-9.]'), ''),
        );
      }

      String? optionalText(String key) {
        final value = decoded[key];
        if (value == null ||
            value is! String ||
            value.trim().isEmpty ||
            value.toLowerCase() == 'null') {
          return null;
        }
        return value.trim();
      }

      final rawCurrency = decoded['currency']?.toString().trim();
      final currency = (rawCurrency == null ||
              rawCurrency.isEmpty ||
              rawCurrency.toLowerCase() == 'null')
          ? AppStrings.currencyDefault
          : rawCurrency;

      final category = decoded['category']?.toString().trim() ??
          optionalText('description') ??
          AppStrings.categoryGeneral;

      if (parsedAmount == null || parsedAmount <= 0) {
        return ExpenseDetectionResult(
          status: ExpenseDetectionStatus.incomplete,
          failureReason: 'Missing or invalid amount.',
          rawOutput: rawResponse,
        );
      }

      final expense = ExpenseDetails(
        amount: parsedAmount,
        currency: currency,
        category: category,
        merchant: optionalText('merchant'),
        date: optionalText('date'),
        description: optionalText('description'),
      );

      return ExpenseDetectionResult(
        status: ExpenseDetectionStatus.complete,
        expense: expense,
        rawOutput: rawResponse,
      );
    } catch (e) {
      return ExpenseDetectionResult(
        status: ExpenseDetectionStatus.incomplete,
        failureReason: 'JSON parsing error: $e',
        rawOutput: rawResponse,
      );
    }
  }

  /// Backward compatibility helper for existing code.
  static ExpenseDetails? tryParse(String response) {
    final result = parseResponse(response);
    return result.expense;
  }

  String toChatResponse() {
    final lines = <String>[
      'Amount: $currency $amount',
      'Category: $category',
      if (merchant != null) 'Merchant: $merchant',
      if (date != null) 'Date: $date',
      if (description != null) 'Description: $description',
    ];
    return lines.join('\n');
  }
}
